### ISSUE TITLE
Conformance Test : 5.5. Output/Capture Image broken

### ISSUE THREAD

**Issue by vryadlapalli** [device-automation-bus/dab-compliance-suite#9]
Hi,

The documentation at https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#55-output shows the response should be a outputImage of type string.

```
Response Format
interface CaptureScreenshotResponse extends DabResponse {
   outputImage: string;
}

```
But the compliance test expects differently. Seems outdated.

```
testing output/image   {"outputLocation": "https://webhook.site/791918a1-cf5f-4a3e-9166-9f83af776232"} ... Traceback (most recent call last):
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/main.py", line 180, in <module>
    Tester.Execute_Test_Case(device_id,(Test_Cases[args.case]))
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/DabTester.py", line 32, in Execute_Test_Case
    if validate_output_function(test_result, durationInMs, expected_response_code) == True:
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/dab/output.py", line 6, in image
    dab_response_validator.validate_output_image_response_schema(test_result.response)
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/schema.py", line 700, in validate_output_image_response_schema
    validate(instance=jsons.loads(response), schema=output_image_response_schema)
  File "/home/vyadlapalli/.local/lib/python3.9/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: 'outputFile' is a required property

Failed validating 'required' in schema:
    {'properties': {'error': {'type': ['string', 'null']},
                    'format': {'type': 'string'},
                    'outputFile': {'type': 'string'},
                    'status': {'type': 'integer'}},
     'required': ['status', 'outputFile', 'format'],
     'type': 'object'}
```

**Comment by bgy36ww** [comment]
Hi, 
this should be resolved in https://github.com/device-automation-bus/dab-compliance-suite/pull/7

**Comment by vryadlapalli** [comment]
This is still failing. It seems like   '**required': ['status', 'outputFile', 'format'**], is not updated.

```

[vyadlapalli@dab-compliance-testing-suite]$ python3.9 main.py -I device0 -c 99

testing output/image   {} ... Traceback (most recent call last):
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/main.py", line 182, in <module>
    Tester.Execute_Test_Case(device_id,(Test_Cases[args.case]))
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/DabTester.py", line 32, in Execute_Test_Case
    if validate_output_function(test_result, durationInMs, expected_response_code) == True:
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/dab/output.py", line 6, in image
    dab_response_validator.validate_output_image_response_schema(test_result.response)
  File "/home/vyadlapalli/rokudev/apps_ndk_git/dab/dab-compliance-testing-suite/schema.py", line 699, in validate_output_image_response_schema
    validate(instance=jsons.loads(response), schema=output_image_response_schema)
  File "/home/vyadlapalli/.local/lib/python3.9/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: 'outputFile' is a required property

Failed validating 'required' in schema:
    {'properties': {'error': {'type': ['string', 'null']},
                    'outputImage': {'type': 'string'},
                    'status': {'type': 'integer'}},
     'required': ['status', 'outputFile', 'format'],
     'type': 'object'}

On instance:
```

**Comment by bgy36ww** [comment]
Sorry! totally missed that. Just submit a quick fix!
